name: chatbot-law
services:
  frontend-angular:
    container_name: $FRONTEND_CONTAINER
    image: $FRONTEND_IMAGE
    build:
      context: ../
      dockerfile: ./frontendv2/deploy/Dockerfile
    restart: always
    networks:
      - chatbot-network
    depends_on:
      authen-service:
        condition: service_healthy

  authen-service:
    container_name: $AUTHEN_CONTAINER
    image: $AUTHEN_IMAGE
    build:
      context: ../
      dockerfile: ./authen-service/Dockerfile
    networks:
      - chatbot-network
    restart: always
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:8080/health || exit 1 "]
      interval: 20s
      timeout: 7s
      retries: 4
      start_period: 30s

  ngrok-service:
    image: ngrok/ngrok
    container_name: $NGROK_CONTAINER
    command: "start my-app-endpoint --config /etc/ngrok.yml"
    volumes:
      - "${NGROK_CONFIG_PATH}:/etc/ngrok.yml"
    depends_on:
      - frontend-angular
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
